# Generated by Django 5.0.14 on 2026-09-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_medicineschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dose", models.CharField(max_length=100)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("taken", "Taken"), ("missed", "Missed"), ("skipped", "Skipped")],
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_history",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="medicines.medicineschedule",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="medicationhistory",
            constraint=models.UniqueConstraint(
                fields=("schedule", "scheduled_at"), name="unique_schedule_occurrence"
            ),
        ),
    ]
