# Generated by Django 5.0.14 on 2026-09-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("taken", "Taken"),
                    ("missed", "Missed"),
                    ("snoozed", "Snoozed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
