# Generated by Django 5.0.14 on 2026-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="dosage",
            field=models.CharField(default="500 mg", max_length=100),
        ),
        migrations.AddField(
            model_name="reminder",
            name="food_timing",
            field=models.CharField(default="after_food", max_length=50),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("taken", "Taken"),
                    ("missed", "Missed"),
                    ("snoozed", "Snoozed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
