# Generated by Django 5.0.14 on 2026-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"ordering": ["dose_datetime"]},
        ),
        migrations.RemoveConstraint(
            model_name="reminder",
            name="uniq_reminder_per_schedule_dose",
        ),
        migrations.RemoveIndex(
            model_name="reminder",
            name="reminders_r_dose_da_a85753_idx",
        ),
        migrations.RemoveIndex(
            model_name="reminder",
            name="reminders_r_reminde_9e30e3_idx",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="dose_date",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="dose_time",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="reminder_time",
        ),
        migrations.AddField(
            model_name="reminder",
            name="dose_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["dose_datetime", "status"], name="reminders_r_dose_da_0870bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["reminder_datetime", "status"], name="reminders_r_reminde_3a8f8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                fields=("schedule", "dose_datetime"), name="uniq_reminder_per_schedule_dose"
            ),
        ),
    ]
