# Generated by Django 5.0.14 on 2026-09-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicationhistory_and_more'),
        ('prescriptions', '0001_initial'),
        ('reminders', '0002_alter_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expiry_reminder', to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medicines.medicineschedule'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prescription__isnull', True), ('schedule__isnull', False)), models.Q(('prescription__isnull', False), ('schedule__isnull', True)), _connector='OR'), name='reminder_has_one_source'),
        ),
    ]
