# Generated by Django 5.0.14 on 2026-09-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_stock', models.PositiveIntegerField(default=0)),
                ('average_daily_consumption', models.FloatField(default=0)),
                ('estimated_depletion_date', models.DateField(blank=True, null=True)),
                ('recommended_refill_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_predictions', to='medications.medicine')),
            ],
        ),
    ]
