# Generated by Django 5.0.14 on 2026-09-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medications", "0002_medication_end_date_medication_food_timing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefillLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity_requested", models.IntegerField(default=60)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Order"),
                            ("approved", "Approved by Pharmacy"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_logs",
                        to="medications.medication",
                    ),
                ),
            ],
        ),
    ]
