# Generated by Django 6.1.1 on 2026-09-09 11:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefillCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_id", models.UUIDField()),
                ("patient_id", models.UUIDField()),
                ("quantity_on_hand", models.FloatField()),
                ("daily_consumption", models.FloatField()),
                ("days_remaining", models.FloatField(blank=True, null=True)),
                ("depletion_date", models.DateField(blank=True, null=True)),
                ("recommended_refill_date", models.DateField(blank=True, null=True)),
                ("is_low_stock", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
