# Generated by Django 6.0.8 on 2026-09-05 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BLOOD_PRESSURE', 'Blood Pressure'), ('DIABETES', 'Diabetes'), ('THYROID', 'Thyroid'), ('ANTIBIOTICS', 'Antibiotics'), ('VITAMINS', 'Vitamins'), ('HEART', 'Heart Medications'), ('OTHER', 'Other')], default='OTHER', help_text='Medicine category most often prescribed for this condition.', max_length=32)),
                ('is_chronic', models.BooleanField(default=True, help_text='Chronic conditions drive long-term adherence tracking and refill prediction.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'medical condition',
                'verbose_name_plural': 'medical conditions',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['category', 'is_active'], name='common_medi_categor_79dd77_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicineReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_ndc', models.CharField(blank=True, db_index=True, help_text='FDA National Drug Code for the product.', max_length=32)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=128)),
                ('route', models.CharField(blank=True, max_length=128)),
                ('strength', models.CharField(blank=True, max_length=64)),
                ('strength_unit', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('BLOOD_PRESSURE', 'Blood Pressure'), ('DIABETES', 'Diabetes'), ('THYROID', 'Thyroid'), ('ANTIBIOTICS', 'Antibiotics'), ('VITAMINS', 'Vitamins'), ('HEART', 'Heart Medications'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32)),
                ('secondary_categories', models.JSONField(blank=True, default=list, help_text='Other categories this medicine also belongs to, e.g. a beta blocker used for both blood pressure and heart conditions.')),
                ('pharm_class', models.CharField(blank=True, max_length=500)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'medicine reference',
                'verbose_name_plural': 'medicine reference',
                'ordering': ('generic_name', 'strength'),
                'indexes': [models.Index(fields=['category', 'is_active'], name='common_medi_categor_96737b_idx'), models.Index(fields=['generic_name', 'brand_name'], name='common_medi_generic_abd427_idx')],
                'constraints': [models.UniqueConstraint(fields=('generic_name', 'dosage_form', 'strength', 'strength_unit'), name='uniq_medicine_reference_presentation')],
            },
        ),
    ]
