# Generated by Django 6.0.8 on 2026-09-05 06:14

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOSE_REMINDER", "Medicine reminder"),
                            ("DOSE_MISSED", "Missed dose"),
                            ("CAREGIVER_ALERT", "Caregiver alert"),
                            ("LOW_STOCK", "Low stock"),
                            ("REFILL_DUE", "Refill due"),
                            ("PRESCRIPTION_EXPIRY", "Prescription expiring"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("PUSH", "Push notification"), ("EMAIL", "Email"), ("SMS", "SMS")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Deep-link data the client app acts on."
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notification",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("dose_reminders", models.BooleanField(default=True)),
                ("missed_dose_alerts", models.BooleanField(default=True)),
                ("refill_alerts", models.BooleanField(default=True)),
                ("caregiver_alerts", models.BooleanField(default=True)),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, default=datetime.time(22, 0), null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
                ),
            ],
            options={
                "verbose_name": "notification preference",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=512, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("WEB", "Web"), ("ANDROID", "Android"), ("IOS", "iOS")],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device token",
                "ordering": ("-created_at",),
            },
        ),
    ]
