# Generated by Django 6.0.8 on 2026-09-05 05:09

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_professional', models.BooleanField(default=False, help_text='A nurse or clinician, as opposed to a family caregiver.')),
                ('is_verified', models.BooleanField(default=False, help_text='An administrator has checked the credentials above.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caregiver profile',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosed_on', models.DateField(blank=True, null=True, validators=[apps.common.validators.validate_not_future])),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('UNKNOWN', 'Not assessed')], default='UNKNOWN', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Cleared infections stay on record but stop driving reminders.')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_links', to='common.medicalcondition')),
            ],
            options={
                'verbose_name': 'patient condition',
                'ordering': ('-is_active', 'condition__name'),
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('relationship_to_manager', models.CharField(blank=True, choices=[('FAMILY', 'Family member'), ('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('PROFESSIONAL', 'Professional caregiver'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('OTHER', 'Other')], help_text='How the managing account relates to this patient. Empty for a self profile.', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[apps.common.validators.validate_not_future])),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('UNDISCLOSED', 'Prefer not to say')], default='UNDISCLOSED', max_length=16)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known drug and food allergies, one per line.')),
                ('notes', models.TextField(blank=True)),
                ('timezone_name', models.CharField(default='UTC', help_text="Reminders fire in the patient's own timezone, not the server's.", max_length=64)),
                ('preferred_reminder_channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='PUSH', max_length=16)),
                ('is_self', models.BooleanField(default=True, help_text='True when the managing user is the patient.')),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='patients', through='profiles.PatientCondition', to='common.medicalcondition')),
                ('managed_by', models.ForeignKey(help_text='The account responsible for this profile. For a self profile this is the same user.', on_delete=django.db.models.deletion.CASCADE, related_name='managed_patient_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='The account this profile belongs to. Empty for a dependent family member who does not sign in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient profile',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_conditions', to='profiles.patientprofile'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('FAMILY', 'Family member'), ('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('PROFESSIONAL', 'Professional caregiver'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('OTHER', 'Other')], default='FAMILY', max_length=20)),
                ('phone_number', models.CharField(max_length=32, validators=[apps.common.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='profiles.patientprofile')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['managed_by', 'is_active'], name='profiles_pa_managed_3e0ad0_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.UniqueConstraint(fields=('managed_by', 'full_name'), name='uniq_profile_name_per_manager'),
        ),
        migrations.AddIndex(
            model_name='patientcondition',
            index=models.Index(fields=['patient', 'is_active'], name='profiles_pa_patient_13ab63_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientcondition',
            constraint=models.UniqueConstraint(fields=('patient', 'condition'), name='uniq_patient_condition'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('patient',), name='uniq_primary_emergency_contact'),
        ),
    ]
