# Generated by Django 5.0.14 on 2026-09-05 14:28

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dosage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("unit", models.CharField(default="tablet", max_length=32)),
                ("instructions", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("dosage_form", models.CharField(blank=True, max_length=128)),
                ("strength", models.CharField(blank=True, max_length=64)),
                ("strength_unit", models.CharField(blank=True, max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BLOOD_PRESSURE", "Blood Pressure"),
                            ("DIABETES", "Diabetes"),
                            ("THYROID", "Thyroid"),
                            ("ANTIBIOTICS", "Antibiotics"),
                            ("VITAMINS", "Vitamins"),
                            ("HEART", "Heart Medications"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                ("instructions", models.CharField(blank=True, max_length=255)),
                (
                    "quantity_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "quantity_per_refill",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5"),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="profiles.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("NIGHT", "Night"),
                        ],
                        default="MORNING",
                        max_length=16,
                    ),
                ),
                ("time_of_day", models.TimeField()),
                (
                    "quantity_per_dose",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Every day"),
                            ("SPECIFIC_DAYS", "On chosen days"),
                            ("INTERVAL", "Every N days"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                (
                    "remind_minutes_before",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(180)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dosage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medications.dosage",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medications.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["time_of_day"],
            },
        ),
        migrations.AddField(
            model_name="dosage",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dosages",
                to="medications.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["patient", "is_active"], name="medications_patient_e6ea57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["patient", "category"], name="medications_patient_8f0d02_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationschedule",
            constraint=models.UniqueConstraint(
                fields=("medicine", "time_of_day", "slot"), name="uniq_schedule_per_medicine_time"
            ),
        ),
    ]
