# Generated by Django 5.0.14 on 2026-09-08 04:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disease_category', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('diabetes', 'Diabetes'), ('thyroid', 'Thyroid'), ('antibiotics', 'Antibiotics'), ('vitamins', 'Vitamins'), ('heart', 'Heart Medications'), ('other', 'Other')], default='other', max_length=40)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('refill_threshold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('exact_time', models.TimeField()),
                ('days_of_week', models.JSONField(default=list)),
                ('dose_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication')),
            ],
            options={
                'ordering': ['exact_time', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.UniqueConstraint(fields=('medication', 'time_of_day', 'exact_time'), name='unique_medication_schedule_time'),
        ),
    ]
