# Generated by Django 6.0.8 on 2026-09-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("medications", "0001_initial"),
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="prescriptions.prescription",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalogue entry this medicine matches, when there is one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_medicines",
                to="common.medicinereference",
            ),
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="medications.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["patient", "is_active"], name="medications_patient_e6ea57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["patient", "category"], name="medications_patient_8f0d02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationschedule",
            index=models.Index(
                fields=["medicine", "is_active"], name="medications_medicin_9d26c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationschedule",
            constraint=models.UniqueConstraint(
                fields=("medicine", "time_of_day", "slot"), name="uniq_schedule_per_medicine_time"
            ),
        ),
    ]
