# Generated by Django 5.0.14 on 2026-09-10 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="food_timing",
            field=models.CharField(
                choices=[
                    ("before_food", "Before Food"),
                    ("after_food", "After Food"),
                    ("with_food", "With Food"),
                    ("empty_stomach", "Empty Stomach"),
                    ("no_preference", "Does Not Matter"),
                ],
                default="after_food",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="medication",
            name="timing_details",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
