# Generated by Django 5.0.10 on 2026-09-10 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='medication',
            name='refill_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='dose_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='morning', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed')], default='pending', max_length=20)),
                ('taken_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='medications.medicationschedule')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='medications.medication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicationhistory',
            constraint=models.UniqueConstraint(fields=('medication', 'dosage_schedule', 'scheduled_datetime'), name='unique_medication_dose_history'),
        ),
    ]
