# Generated by Django 5.0.14 on 2026-10-05 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medications", "0002_medication_end_date_medication_food_timing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="assigned_patient_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="assigned_patient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
