"""add reminder scheduling and snooze fields

Revision ID: 136a6446de76
Revises: 395a455b056c
Create Date: 2026-09-06 03:02:01.293501

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "136a6446de76"
down_revision: str | None = "395a455b056c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminders", sa.Column("day_of_week", sa.Integer(), nullable=True))
    op.add_column("reminders", sa.Column("interval_days", sa.Integer(), nullable=True))
    op.add_column(
        "reminders", sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

    # Note: no new Postgres ENUM types were introduced by this revision (unlike
    # the initial migration), so downgrade() below doesn't need the explicit
    # `sa.Enum(...).drop(...)` calls that pattern requires.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reminders", "snoozed_until")
    op.drop_column("reminders", "interval_days")
    op.drop_column("reminders", "day_of_week")
    # ### end Alembic commands ###
