"""initial schema: users, profiles, caregiver mapping, medicines, reminders, adherence, refills

Revision ID: 395a455b056c
Revises:
Create Date: 2026-08-30 16:30:59.544489

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "395a455b056c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column(
            "role", sa.Enum("PATIENT", "CAREGIVER", "ADMIN", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "caregiver_patient_mapping",
        sa.Column("caregiver_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum(
                "VIEW_ONLY", "MANAGE_MEDICATIONS", "FULL_ACCESS", name="caregiver_access_level"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="caregiver_mapping_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["caregiver_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_caregiver_patient_mapping_caregiver_id"),
        "caregiver_patient_mapping",
        ["caregiver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_caregiver_patient_mapping_id"), "caregiver_patient_mapping", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_caregiver_patient_mapping_patient_id"),
        "caregiver_patient_mapping",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "medicines",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dosage", sa.String(length=100), nullable=False),
        sa.Column(
            "form",
            sa.Enum(
                "TABLET",
                "CAPSULE",
                "SYRUP",
                "INJECTION",
                "DROPS",
                "INHALER",
                "OTHER",
                name="medicine_form",
            ),
            nullable=False,
        ),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False),
        sa.Column("refill_threshold", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medicines_id"), "medicines", ["id"], unique=False)
    op.create_index(op.f("ix_medicines_name"), "medicines", ["name"], unique=False)
    op.create_index(op.f("ix_medicines_user_id"), "medicines", ["user_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("emergency_contact", sa.String(length=150), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("medical_history_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_profiles_id"), "user_profiles", ["id"], unique=False)
    op.create_index(op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True)
    op.create_table(
        "refill_logs",
        sa.Column("medicine_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_added", sa.Integer(), nullable=False),
        sa.Column("estimated_depletion_date", sa.Date(), nullable=True),
        sa.Column(
            "logged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["medicine_id"], ["medicines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refill_logs_id"), "refill_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_refill_logs_medicine_id"), "refill_logs", ["medicine_id"], unique=False
    )
    op.create_table(
        "reminders",
        sa.Column("medicine_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "ONCE_DAILY",
                "TWICE_DAILY",
                "THREE_TIMES_DAILY",
                "WEEKLY",
                "AS_NEEDED",
                "CUSTOM",
                name="reminder_frequency",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["medicine_id"], ["medicines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminders_id"), "reminders", ["id"], unique=False)
    op.create_index(op.f("ix_reminders_medicine_id"), "reminders", ["medicine_id"], unique=False)
    op.create_index(op.f("ix_reminders_user_id"), "reminders", ["user_id"], unique=False)
    op.create_table(
        "adherence_logs",
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("TAKEN", "MISSED", "SNOOZED", name="adherence_status"), nullable=False
        ),
        sa.Column(
            "logged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["reminder_id"], ["reminders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adherence_logs_id"), "adherence_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_adherence_logs_reminder_id"), "adherence_logs", ["reminder_id"], unique=False
    )
    op.create_index(op.f("ix_adherence_logs_user_id"), "adherence_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adherence_logs_user_id"), table_name="adherence_logs")
    op.drop_index(op.f("ix_adherence_logs_reminder_id"), table_name="adherence_logs")
    op.drop_index(op.f("ix_adherence_logs_id"), table_name="adherence_logs")
    op.drop_table("adherence_logs")
    op.drop_index(op.f("ix_reminders_user_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_medicine_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_id"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_refill_logs_medicine_id"), table_name="refill_logs")
    op.drop_index(op.f("ix_refill_logs_id"), table_name="refill_logs")
    op.drop_table("refill_logs")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_medicines_user_id"), table_name="medicines")
    op.drop_index(op.f("ix_medicines_name"), table_name="medicines")
    op.drop_index(op.f("ix_medicines_id"), table_name="medicines")
    op.drop_table("medicines")
    op.drop_index(
        op.f("ix_caregiver_patient_mapping_patient_id"), table_name="caregiver_patient_mapping"
    )
    op.drop_index(op.f("ix_caregiver_patient_mapping_id"), table_name="caregiver_patient_mapping")
    op.drop_index(
        op.f("ix_caregiver_patient_mapping_caregiver_id"), table_name="caregiver_patient_mapping"
    )
    op.drop_table("caregiver_patient_mapping")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Alembic's autogenerate drops the tables above but, on PostgreSQL, native
    # ENUM types are separate objects that survive a `DROP TABLE`. Drop them
    # explicitly here or a later `upgrade` recreating the same table collides
    # with `DuplicateObjectError: type "..." already exists`.
    bind = op.get_bind()
    sa.Enum(name="adherence_status").drop(bind, checkfirst=True)
    sa.Enum(name="reminder_frequency").drop(bind, checkfirst=True)
    sa.Enum(name="medicine_form").drop(bind, checkfirst=True)
    sa.Enum(name="caregiver_mapping_status").drop(bind, checkfirst=True)
    sa.Enum(name="caregiver_access_level").drop(bind, checkfirst=True)
    sa.Enum(name="user_role").drop(bind, checkfirst=True)
