# Generated by Django 6.0.8 on 2026-09-05 05:09

import apps.accounts.models
import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone_number', models.CharField(blank=True, max_length=32, validators=[apps.common.validators.validate_phone_number])),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('CAREGIVER', 'Caregiver'), ('ADMIN', 'Admin')], db_index=True, default='PATIENT', max_length=16)),
                ('auth_provider', models.CharField(choices=[('LOCAL', 'Email and password'), ('GOOGLE', 'Google')], default='LOCAL', max_length=16)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting: medication history must survive.')),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('FAMILY', 'Family member'), ('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('PROFESSIONAL', 'Professional caregiver'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('OTHER', 'Other')], default='FAMILY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending patient approval'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=16)),
                ('can_view_adherence', models.BooleanField(default=True)),
                ('can_receive_alerts', models.BooleanField(default=True)),
                ('can_manage_medications', models.BooleanField(default=False, help_text='Off by default: viewing a medication schedule and changing it are very different levels of trust.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'CAREGIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caregiver assignment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverassignment',
            index=models.Index(fields=['patient', 'status'], name='accounts_ca_patient_6dc13f_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregiverassignment',
            constraint=models.UniqueConstraint(fields=('caregiver', 'patient'), name='uniq_caregiver_patient'),
        ),
        migrations.AddConstraint(
            model_name='caregiverassignment',
            constraint=models.CheckConstraint(condition=models.Q(('caregiver', models.F('patient')), _negated=True), name='caregiver_is_not_patient'),
        ),
    ]
