# Generated by Django 6.0.8 on 2026-09-30 06:10

import apps.ocr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("medications", "0002_initial"),
        ("prescriptions", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PRESCRIPTION", "Prescription"),
                            ("MEDICINE_LABEL", "Medicine box or strip"),
                        ],
                        default="PRESCRIPTION",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("IMAGE", "Uploaded image"), ("TEXT", "Typed or pasted text")],
                        default="IMAGE",
                        max_length=8,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.ocr.models.ocr_upload_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Ready to review"),
                            ("FAILED", "Failed"),
                            ("CONFIRMED", "Added to medicines"),
                            ("REJECTED", "Discarded"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("engine", models.CharField(blank=True, max_length=64)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Mean word confidence reported by the OCR engine, 0-1.",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Overall confidence in the extraction, 0-1. Combines OCR quality with how complete and how well matched the extracted medicines are.",
                        null=True,
                    ),
                ),
                ("header", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("processing_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_jobs",
                        to="profiles.patientprofile",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_jobs",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR job",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExtractedMedicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("raw_line", models.TextField(blank=True)),
                ("name", models.CharField(max_length=255)),
                ("form", models.CharField(blank=True, max_length=64)),
                ("strength", models.CharField(blank=True, max_length=64)),
                ("strength_unit", models.CharField(blank=True, max_length=64)),
                ("slots", models.JSONField(blank=True, default=list)),
                ("frequency", models.CharField(default="DAILY", max_length=16)),
                ("interval_days", models.PositiveSmallIntegerField(default=1)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("as_needed", models.BooleanField(default=False)),
                ("duration_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "total_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("instructions", models.CharField(blank=True, max_length=255)),
                (
                    "match_level",
                    models.CharField(
                        choices=[
                            ("AUTO", "Matched"),
                            ("POSSIBLE", "Possible match"),
                            ("NONE", "No match"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                ("match_score", models.FloatField(default=0.0)),
                (
                    "suggestions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Catalogue candidates the patient can choose between: [{id, label, category, score}].",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "To review"),
                            ("CONFIRMED", "Added"),
                            ("REJECTED", "Left out"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_items",
                        to="medications.medicine",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for a confident match, or once the patient picks one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_items",
                        to="common.medicinereference",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ocr.ocrjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "extracted medicine",
                "ordering": ("job", "position"),
            },
        ),
        migrations.AddIndex(
            model_name="ocrjob",
            index=models.Index(fields=["patient", "status"], name="ocr_ocrjob_patient_2e3167_idx"),
        ),
    ]
