# Generated by Django 6.1.1 on 2026-09-09 11:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrescriptionScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.UUIDField()),
                ("image", models.ImageField(upload_to="prescription_scans/")),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "medicine_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("dosage", models.CharField(blank=True, default="", max_length=100)),
                ("quantity", models.CharField(blank=True, default="", max_length=100)),
                ("frequency", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
