# Generated by Django 6.1 on 2026-09-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('confidence_level', models.CharField(default='Medium', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription Upload',
                'verbose_name_plural': 'Prescription Uploads',
                'db_table': 'prescription_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
