# Generated by Django 5.0.14 on 2026-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrrecord",
            name="dosage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="frequency",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="medicine_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="prescription_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ocrrecord",
            name="quantity",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
