# Generated by Django 5.0.14 on 2026-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0002_ocrrecord_dosage_ocrrecord_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrrecord",
            name="is_uncertain",
            field=models.BooleanField(default=False),
        ),
    ]
