import { useEffect, useState } from 'react';
import { Bell, Check, Clock3, X } from 'lucide-react';
import Button from '../../components/Button';
import Card from '../../components/Card';
import EmptyState from '../../components/EmptyState';
import ErrorMessage from '../../components/ErrorMessage';
import Loading from '../../components/Loading';
import { getApiErrorMessage } from '../../services/api';
import { medicationService } from '../../services/medicationService';

const Notifications = () => {
  const [reminders, setReminders] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [feedback, setFeedback] = useState('');
  const load = async () => { setLoading(true); try { setReminders(await medicationService.listReminders()); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to load reminders.')); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, []);
  const action = async (id, operation, label) => { setError(''); try { const updated = operation === 'snooze' ? await medicationService.snoozeReminder(id, 30) : await operation(id); setReminders((current) => current.map((reminder) => reminder.id === id ? updated : reminder)); setFeedback(label); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to update reminder.')); } };
  return <div className="max-w-4xl mx-auto space-y-6 animate-fade-in" data-testid="notifications-page"><div><h1 className="text-xl font-extrabold text-slate-800 tracking-tight">Reminders</h1><p className="text-xs text-slate-450 mt-0.5">Take action on scheduled medication reminders.</p></div>{feedback && <div role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">{feedback}</div>}{error && <ErrorMessage message={error} onDismiss={() => setError('')} />}{loading ? <Loading text="Loading reminders..." /> : reminders.length === 0 ? <EmptyState title="No reminders yet" description="Reminders will appear when active schedules generate occurrences." /> : <div className="space-y-3">{reminders.map((reminder) => { const complete = ['taken', 'missed'].includes(reminder.status); return <Card key={reminder.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-lg bg-brand-50 p-2 text-brand-600"><Bell className="h-5 w-5" /></div><div><h2 className="text-sm font-bold text-slate-800">Scheduled dose</h2><p className="text-xs text-slate-500 mt-1">{new Date(reminder.scheduled_at).toLocaleString()} · {reminder.period}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold capitalize text-slate-600">{reminder.status}</span></div></div><div className="flex flex-wrap justify-end gap-2">{!complete && <><Button variant="primary" onClick={() => action(reminder.id, medicationService.markReminderTaken, 'Reminder marked taken.')} className="!py-1.5 !px-2.5 text-xs"><Check className="mr-1 h-3.5 w-3.5" />Taken</Button><Button variant="outline" onClick={() => action(reminder.id, medicationService.markReminderMissed, 'Reminder marked missed.')} className="!py-1.5 !px-2.5 text-xs"><X className="mr-1 h-3.5 w-3.5" />Missed</Button><Button variant="secondary" onClick={() => action(reminder.id, 'snooze', 'Reminder snoozed for 30 minutes.')} className="!py-1.5 !px-2.5 text-xs"><Clock3 className="mr-1 h-3.5 w-3.5" />Snooze</Button></>}</div></div></Card>; })}</div>}</div>;
};
export default Notifications;
