# Generated by Django 6.0.8 on 2026-09-05 06:14

import apps.common.validators
import apps.prescriptions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                ("reference_number", models.CharField(blank=True, max_length=64)),
                (
                    "issued_on",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[apps.common.validators.validate_not_future],
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="Repeat prescriptions run out; the patient is reminded before they do.",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.prescriptions.models.prescription_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("ocr_extracted", models.BooleanField(default=False)),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="0-1. Low confidence means a human should check the extracted fields.",
                        null=True,
                    ),
                ),
                ("ocr_raw_text", models.TextField(blank=True)),
                (
                    "expiry_reminded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the expiry reminder went out, so it is not sent twice.",
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="profiles.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription",
                "ordering": ("-issued_on", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["patient", "status"], name="prescriptio_patient_283c70_idx"
                    ),
                    models.Index(fields=["expires_on"], name="prescriptio_expires_7b0a89_idx"),
                ],
            },
        ),
    ]
