# Generated by Django 5.0.14 on 2026-09-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medications", "0002_medication_end_date_medication_food_timing_and_more"),
        ("reminders", "0002_reminder_dosage_reminder_food_timing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdherenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("taken", "Taken"), ("missed", "Missed"), ("snoozed", "Snoozed")],
                        default="taken",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Night", "Night"),
                        ],
                        default="Morning",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.CharField(default="08:00 AM", max_length=50)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adherence_logs",
                        to="medications.medication",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adherence_logs",
                        to="reminders.reminder",
                    ),
                ),
            ],
        ),
    ]
