# Generated by Django 5.0.14 on 2026-09-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('snoozed', 'Snoozed')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_events', to='medications.medication')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_events', to='medications.medicationschedule')),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
                'indexes': [models.Index(fields=['medication', 'scheduled_for'], name='adherence_d_medicat_a2a835_idx'), models.Index(fields=['status', 'scheduled_for'], name='adherence_d_status_c17a0a_idx')],
            },
        ),
    ]
