# Generated by Django 5.2.17 on 2026-09-20 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dose_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("TAKEN", "Taken"), ("MISSED", "Missed"), ("SNOOZED", "Snoozed")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("missed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_events",
                        to="medications.medicationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-dose_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["dose_date", "status"], name="dose_event_date_status_idx"),
                    models.Index(
                        fields=["schedule", "dose_date"], name="dose_event_schedule_date_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "dose_date"), name="unique_dose_event_per_schedule_date"
                    )
                ],
            },
        ),
    ]
