# Generated by Django 6.0.6 on 2026-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medication_quantity_medication_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adherencerecord',
            name='status',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Pending', 'Pending'), ('Missed', 'Missed'), ('Snoozed', 'Snoozed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Taken', 'Taken'), ('Pending', 'Pending'), ('Missed', 'Missed'), ('Snoozed', 'Snoozed')], default='Pending', max_length=20),
        ),
    ]
